# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_broadcast_channel"
<<<<<<< HEAD
version = "0.135.0"
=======
version = "0.136.0"
>>>>>>> 0d7662e15 (1.41.3 (#22925))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Implementation of BroadcastChannel API for Deno"

[lib]
path = "lib.rs"

[dependencies]
async-trait.workspace = true
deno_core.workspace = true
tokio.workspace = true
uuid.workspace = true
