# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_console"
<<<<<<< HEAD
version = "0.141.0"
=======
version = "0.142.0"
>>>>>>> 0d7662e15 (1.41.3 (#22925))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Implementation of Console API for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true
