# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_console"
<<<<<<< HEAD
version = "0.129.0"
=======
version = "0.130.0"
>>>>>>> 6af25c059 (1.39.2 (#21791))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "Implementation of Console API for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true
