# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "napi_sym"
<<<<<<< HEAD
version = "0.81.0"
=======
version = "0.82.0"
>>>>>>> d64921c19 (1.43.4 (#23853))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "proc macro for writing N-API symbols"

[lib]
path = "./lib.rs"
proc-macro = true

[dependencies]
quote.workspace = true
serde.workspace = true
serde_json.workspace = true
syn.workspace = true
