# Copyright 2018-2024 the Deno authors. All rights reserved. MIT license.

[package]
name = "deno_napi"
<<<<<<< HEAD
version = "0.59.0"
=======
version = "0.60.0"
>>>>>>> 6af25c059 (1.39.2 (#21791))
authors.workspace = true
edition.workspace = true
license.workspace = true
readme = "README.md"
repository.workspace = true
description = "NAPI implementation for Deno"

[lib]
path = "lib.rs"

[dependencies]
deno_core.workspace = true
libloading = { version = "0.7" }
